apiVersion: batch.github.com/v1
kind: Obzev0Resource
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: obzev0resource-sample
spec:
  latencySvcConfig:
    enabled: true 
    reqDelay: 1 
    resDelay: 1 
    server: "7070"
    client: "10.244.2.4:8080"
  tcAnalyserSvcConfig:
    enabled: false
    netIFace: "eth0"
  packetManipulationSvcConfig:
    enabled: true 
    server: "9091"
    client: "10.244.2.4:8080"
    dropRate: "0.8"
    corruptRate: "0.4"
    durationSeconds: 8 
status:
  message: "Server started successfully"

