apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
      - name: my-express
        image: lumbrjx/my-express:latest # Use the name and tag of your Docker image
        ports:
        - containerPort: 8080

