apiVersion: v2
name: obzev0
description: A Helm chart for deploying the Obzev0 application on Kubernetes.

# A chart can be either an 'application' or a 'library' chart.
# Application charts are collections of templates that define resources to be deployed.
# Library charts provide utilities or functions to be used by other charts.
type: application

# This is the chart version. Increment this version number each time you make changes
# to the chart itself or its templates. Follow Semantic Versioning (https://semver.org/).
version: 0.1.0

# This is the version number of the application being deployed. Increment this version
# number to reflect changes to the application. This version does not follow Semantic
# Versioning but should accurately reflect the application's version.
appVersion: "1.16.0"

# Define the Kubernetes API version of the chart (v2 is recommended for Helm 3+).
# Ensure compatibility with the Helm version being used.
apiVersion: v2

# Maintainer information (optional but recommended).
maintainers:
  - name: Lumberjack 

