apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grpc-server-daemonset
  labels:
    app: grpc-server
spec:
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: lumbrjx/obzev0-grpc-daemon:1.0.1  
        ports:
        - containerPort: 50051  
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 10
      nodeSelector:
        node-role.kubernetes.io/worker: ""  
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

