apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  labels:
    app: grpc-server
spec:
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    app: grpc-server
  type: NodePort 

