name: Publish Helm Chart

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.15.3

    - name: Package Helm chart
      run: |
        if [ -f charts/Chart.yaml ]; then
          helm package charts
        else
          echo "Chart.yaml not found in the charts directory"
          exit 1
        fi

    - name: Create or update index.yaml
      run: |
        if [ ! -f index.yaml ]; then
          helm repo index .
        else
          helm repo index . --merge index.yaml
        fi

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}  # Use the secret for authentication
      run: |
        git add .
        git commit -m "Update Helm charts"
        git push https://x-access-token:${GH_PAT}@github.com/lumbrjx/obzev0.git staging

